dataset = "../data_test"
checkpoint_save_path = "out"
resume = 70
batch_size = 12
image_shape = [ 256, 256, 1,]
mask_shape = [ 128, 128,]
mask_batch_same = true
max_delta_shape = [ 32, 32,]
margin = [ 0, 0,]
discounted_mask = true
spatial_discounting_gamma = 0.9
random_crop = true

# Training Parameters
expname = "benchmark"
cuda = true
n_cpu = 16
lr = 0.0001
beta1 = 0.5
beta2 = 0.9
n_critic = 5
epochs = 1000
print_iter = 1
viz_iter = 1
viz_max_out = 12
snapshot_save_iter = 2

# Loss weight
coarse_l1_alpha = 1.2
l1_loss_alpha = 1.2
ae_loss_alpha = 1.2
global_wgan_loss_alpha = 1.0
gan_loss_alpha = 0.001
wgan_gp_lambda = 10

# Network parameters
input_dim = 1
ngf = 32
ndf = 64
